#!/usr/bin/env python3
"""Bake SFX WAV files (or synthesize placeholders) into a C header."""
import math, os, struct, sys, wave
from pathlib import Path

RATE = 16000
ASSETS = [
    ("sfx_rec_start", "rec_start.wav", 0.08, "click"),
    ("sfx_rec_send",  "rec_send.wav",  0.12, "kick"),
    ("sfx_note_c",    "note_c.wav",    0.25, ("tone", 523.25)),
    ("sfx_note_d",    "note_d.wav",    0.25, ("tone", 587.33)),
    ("sfx_note_e",    "note_e.wav",    0.25, ("tone", 659.25)),
    ("sfx_note_g",    "note_g.wav",    0.25, ("tone", 783.99)),
    ("sfx_note_a",    "note_a.wav",    0.25, ("tone", 880.00)),
    ("sfx_bed_loop",  "bed_loop.wav",  2.00, "bed"),
    ("sfx_error",     "error.wav",     0.40, "error"),
]

def synth(kind, duration):
    n = int(RATE * duration)
    out = []
    if isinstance(kind, tuple) and kind[0] == "tone":
        freq = kind[1]
        for i in range(n):
            env = math.exp(-3.0 * i / n)
            s = 0.3 * env * math.sin(2 * math.pi * freq * i / RATE)
            out.append(int(s * 32000))
    elif kind == "click":
        for i in range(n):
            env = math.exp(-30.0 * i / n)
            s = 0.4 * env * math.sin(2 * math.pi * 3000 * i / RATE)
            out.append(int(s * 32000))
    elif kind == "kick":
        for i in range(n):
            env = math.exp(-10.0 * i / n)
            freq = 120 * math.exp(-5.0 * i / n) + 50
            s = 0.6 * env * math.sin(2 * math.pi * freq * i / RATE)
            out.append(int(s * 32000))
    elif kind == "bed":
        for i in range(n):
            beat = (i // (RATE // 4)) % 4
            click = 1.0 if (i % (RATE // 4)) < (RATE // 40) else 0.0
            s = 0.08 * click * math.sin(2 * math.pi * (60 if beat == 0 else 200) * i / RATE)
            out.append(int(s * 32000))
    elif kind == "error":
        half = n // 2
        for i in range(n):
            freq = 400 if i < half else 330
            env = math.exp(-2.0 * (i % half) / half)
            s = 0.3 * env * math.sin(2 * math.pi * freq * i / RATE)
            out.append(int(s * 32000))
    return out

def load_wav_s16_16k_mono(path):
    with wave.open(str(path), "rb") as w:
        if w.getframerate() != RATE or w.getnchannels() != 1 or w.getsampwidth() != 2:
            raise SystemExit(f"{path}: must be {RATE} Hz mono 16-bit PCM")
        raw = w.readframes(w.getnframes())
    return list(struct.unpack(f"<{len(raw)//2}h", raw))

def main():
    root = Path(__file__).resolve().parents[1]
    src_dir = root / "assets" / "sfx"
    out_path = root / "src" / "audio" / "sfx_assets.h"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    parts = ["// GENERATED by tools/bake_sfx.py - do not edit by hand.",
             "#pragma once", "#include <cstdint>", "#include <cstddef>", ""]
    total = 0
    for sym, fname, dur, kind in ASSETS:
        path = src_dir / fname
        if path.exists():
            samples = load_wav_s16_16k_mono(path)
        else:
            samples = synth(kind, dur)
        parts.append(f"static const int16_t {sym}_data[{len(samples)}] = {{")
        for i in range(0, len(samples), 16):
            row = ",".join(str(s) for s in samples[i:i+16])
            parts.append(f"    {row},")
        parts.append("};")
        parts.append(f"static constexpr size_t {sym}_len = {len(samples)};")
        parts.append("")
        total += len(samples) * 2
    parts.append(f"// Total SFX bytes: {total}")
    out_path.write_text("\n".join(parts))
    print(f"baked {len(ASSETS)} assets, {total} bytes -> {out_path}")

if __name__ == "__main__":
    main()
